"""The deploy scripts, and the two ways they are allowed to fail.

``install.sh`` and ``rollback.sh`` are the only things standing between a bad
configuration and a site that does not come back. Both are held to the same rule the
application follows: nothing is replaced until a copy of what it is replacing exists
and verifies, and no configuration file is swapped in until ``nginx -t`` has accepted
it — because Nginx reads its configuration on reload, not on write.

Each script is run for real, against a whole production layout in a temporary
directory with ``nginx``, ``systemctl``, ``curl``, ``id``, ``chown``, ``useradd``,
``visudo`` and ``install`` stubbed and instrumented. The stubs record what they were
asked to do, which is how the ordering assertions are made: that the snapshot is
written before the first thing is replaced, and that the reload never happens when
the test failed.

That is the same approach ``test_decommission.py`` uses, for the same reason — the
scripts keep literal absolute paths because a path that can be steered is a path that
can be aimed at the wrong file, so the sandbox rewrites them instead.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
INAUGURATION = REPO / "inauguration"
INSTALL = INAUGURATION / "deploy" / "install.sh"
ROLLBACK = INAUGURATION / "deploy" / "rollback.sh"
SMOKE = INAUGURATION / "deploy" / "smoke.sh"
UNIT = INAUGURATION / "deploy" / "systemd" / "nss-inauguration.service"
SUDOERS = INAUGURATION / "deploy" / "sudoers" / "nss-inauguration"
NGINX_SITE = INAUGURATION / "deploy" / "nginx" / "nss"

BASH = shutil.which("bash")

pytestmark = pytest.mark.skipif(BASH is None, reason="bash is required to run the deploy scripts")


# ---------------------------------------------------------------------------
# Static reading of the shipped files
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def install_source() -> str:
    return INSTALL.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def rollback_source() -> str:
    return ROLLBACK.read_text(encoding="utf-8")


def test_install_takes_no_arguments(install_source: str):
    assert re.search(r'\[ "\$#" -eq 0 \]', install_source), "no argument count check"
    assert 'die "this script takes no arguments"' in install_source


def test_install_backs_up_before_it_changes_anything(install_source: str):
    """The snapshot is the way back, so it has to exist before the first write.

    Asserted on the order of the calls in main(), not on the order the functions are
    defined in — a reordering of the definitions changes nothing.
    """
    body = install_source[install_source.index("main() {") :]
    order = [
        name
        for name in re.findall(r"^\s{4}(phase_\d+_\w+)", body, re.M)
    ]
    assert order, "no phase calls found in main()"
    assert order[1] == "phase_1_backup", f"the backup is not the second phase: {order}"
    assert order.index("phase_1_backup") < order.index("phase_5_web_files")
    assert order.index("phase_1_backup") < order.index("phase_6_decommission")
    assert order.index("phase_1_backup") < order.index("phase_7_nginx")


def test_install_verifies_the_snapshot_it_takes(install_source: str):
    assert "MANIFEST.sha256" in install_source
    assert "sha256sum -c" in install_source or "sha256sum --check" in install_source


def test_install_tests_nginx_before_it_reloads(install_source: str):
    """The whole safety argument for replacing a live configuration."""
    nginx_phase = install_source[
        install_source.index("phase_7_nginx()") : install_source.index("phase_8_systemd()")
    ]
    first_test = nginx_phase.index('"$NGINX_BIN" -t')
    first_reload = nginx_phase.index('"$NGINX_BIN" -s reload')
    assert first_test < first_reload, "nginx is reloaded before it is tested"
    assert "rollback_site" in nginx_phase, "a failed test does not restore the previous file"


def test_install_validates_sudoers_before_installing_it(install_source: str):
    """A broken file in /etc/sudoers.d takes sudo away from everyone, including
    whoever is trying to fix it."""
    phase = install_source[
        install_source.index("phase_9_sudoers()") : install_source.index("phase_10_start()")
    ]
    assert "visudo -cf" in phase, "the rule is not validated"
    assert phase.index("visudo -cf") < phase.index('mv "$candidate" "$SUDOERS"')
    assert phase.index('install -o root -g root -m 0440') < phase.index("visudo -cf"), (
        "the rule is installed into /etc/sudoers.d before it is validated"
    )


def test_install_never_writes_a_secret(install_source: str):
    """The session key is generated by the application on first boot."""
    assert "NSS_ADMIN_PASSWORD" not in install_source
    assert "secret.key" not in install_source


def test_rollback_gates_the_web_restore_on_the_flag(rollback_source: str):
    """The site's content is not what breaks, and rewriting it during an incident
    would undo whatever the ceremony had legitimately done.

    The behavioural half of this is the sandboxed run further down; this is the
    structural half. They are deliberately separate tests — a rename once made them
    share a name, and the second silently shadowed this one so it never ran.
    """
    body = rollback_source[rollback_source.index("main() {") :]
    assert '[ "$want_web" -eq 1 ] && restore_web' in body, (
        "restore_web is not gated on --web"
    )


def test_rollback_verifies_the_snapshot_before_using_it(rollback_source: str):
    body = rollback_source[rollback_source.index("main() {") :]
    assert body.index("verify_snapshot") < body.index("restore_nginx"), (
        "a snapshot is restored without checking its checksums first"
    )
    assert "does not match its own checksums" in rollback_source


def test_rollback_stashes_what_it_replaces(rollback_source: str):
    """If the rollback turns out to be the wrong move, the state it replaced is
    still on disk."""
    body = rollback_source[rollback_source.index("main() {") :]
    assert body.index("backup_current") < body.index("restore_nginx")
    assert "pre-rollback-" in rollback_source


# ---------------------------------------------------------------------------
# The shipped configuration files
# ---------------------------------------------------------------------------


def _strip_comments(text: str) -> str:
    """Drop whole-line comments, so a directive named in prose is not mistaken for
    one that is set. Every file here uses `#`."""
    return "\n".join(
        line for line in text.splitlines() if not line.strip().startswith("#")
    )


def _server_blocks(text: str) -> list[str]:
    """The `server { ... }` blocks of an Nginx file, braces balanced."""
    blocks, depth, start = [], 0, None
    for index, line in enumerate(text.splitlines()):
        if line.strip() == "server {":
            start = index
        if start is not None:
            depth += line.count("{") - line.count("}")
            if depth == 0:
                blocks.append("\n".join(text.splitlines()[start : index + 1]))
                start = None
    return blocks


def test_the_server_block_does_not_redefine_the_include_locations():
    """The include owns `location /` and `location ^~ /api/` in every mode.

    A second copy of either is a duplicate-location error, so `nginx -t` would fail
    at install time — on the one morning there is no room for it.

    Only the TLS server is checked: the port-80 block is a redirect and includes
    nothing, so its `location /` is both correct and necessary.
    """
    blocks = _server_blocks(NGINX_SITE.read_text(encoding="utf-8"))
    assert len(blocks) == 2, f"expected a redirect and a TLS server block, found {len(blocks)}"

    tls = [b for b in blocks if "listen      443 ssl;" in b]
    assert len(tls) == 1, "could not identify the TLS server block"
    code = _strip_comments(tls[0])

    assert "location / {" not in code, "the server block defines `location /`"
    assert "location ^~ /api/" not in code, "the server block defines the API location"
    assert "location ^~ /admin/" not in code, "the server block defines the portal location"
    assert "include /etc/nginx/nss-mode.inc;" in code


def test_the_server_block_forwards_the_client_address():
    """Without this the login lockout keys on 127.0.0.1 and one attacker locks out
    every admin, or none of them."""
    code = _strip_comments(NGINX_SITE.read_text(encoding="utf-8"))
    assert "proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;" in code


def test_the_server_block_sends_no_frame_denial():
    """The ceremony's reveal frames index.html inside its own page. A DENY here
    replaces the climax of the ceremony with a browser error page."""
    code = _strip_comments(NGINX_SITE.read_text(encoding="utf-8"))
    assert "X-Frame-Options" not in code


def test_the_unit_does_not_run_as_root():
    text = UNIT.read_text(encoding="utf-8")
    assert "User=nss-inaug" in text
    assert "User=root" not in _strip_comments(text)


def test_the_unit_only_writes_the_three_declared_paths():
    text = UNIT.read_text(encoding="utf-8")
    code = _strip_comments(text)
    writable = set(re.findall(r"^ReadWritePaths=(\S+)$", code, re.M))
    assert writable == {
        "/opt/nss-inauguration/config",
        "/var/backups/nss-inauguration",
        "/etc/nginx/nss-mode.inc",
    }, "the writable set changed; review what the service can now reach"
    # Explicitly not the web root, and explicitly not the server block.
    assert "/var/www/nss" not in code
    assert "/etc/nginx/sites-available/nss" not in code


def test_the_unit_explains_the_two_directives_it_omits():
    """NoNewPrivileges and SystemCallFilter=@system-service both break `sudo`, which
    is the only path to the cleanup. The omission is deliberate and has to stay
    legible, or the next person adds them back and breaks the one irreversible
    operation."""
    text = UNIT.read_text(encoding="utf-8")
    code = _strip_comments(text)
    assert "NoNewPrivileges" not in code, "it is set, and sudo will fail"
    assert "SystemCallFilter" not in code
    assert "NoNewPrivileges" in text, "the reason for the omission was deleted"
    assert "PR_SET_NO_NEW_PRIVS" in text


def test_the_sudoers_rule_forbids_arguments():
    """A command listed without an argument spec may be run with *any* arguments.
    The trailing "" is what makes the no-arguments guarantee enforced rather than
    merely intended."""
    text = SUDOERS.read_text(encoding="utf-8")
    rules = [
        line for line in text.splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    grants = [line for line in rules if "NOPASSWD" in line]
    assert len(grants) == 1, f"expected exactly one grant, found {len(grants)}"
    assert grants[0].strip().endswith('/usr/local/sbin/nss-decommission ""'), (
        "the rule does not restrict the argument vector"
    )
    assert "ALL=(root)" in grants[0]
    assert "ALL=NOPASSWD" not in grants[0].replace("ALL=(root) NOPASSWD", "")


def test_smoke_covers_every_required_reachable_path():
    """nginx_mode.REQUIRED_REACHABLE is the one list of paths that must answer in
    every mode. The smoke script keeps its own literal copy so it does not need the
    application to run; this is what stops the two drifting apart.
    """
    sys.path.insert(0, str(INAUGURATION / "backend"))
    from app.nginx_mode import REQUIRED_REACHABLE, render_include

    text = SMOKE.read_text(encoding="utf-8")
    for path in REQUIRED_REACHABLE:
        if path == "/assets/":
            # A prefix, not a file. The smoke script fetches a real file beneath it,
            # and the rendered include must serve the prefix ahead of the regex that
            # redirects every .html — otherwise a JPEG 404s on the hold page.
            assert "/assets/events/blood/blood-1.jpg" in text, (
                "smoke.sh has no concrete file to request under /assets/"
            )
            rendered = render_include("coming_soon")
            assert "location ^~ /assets/" in rendered
            assert rendered.index("location ^~ /assets/") < rendered.index(r"location ~* \.html$"), (
                "the asset prefix does not precede the catch-all, so ^~ is doing nothing"
            )
            continue
        assert path in text, f"smoke.sh never checks {path}"


def test_smoke_treats_the_missing_favicon_as_expected():
    """There is no favicon.ico in this repository and never has been. 404 is the
    correct answer for it; what would be a bug is a redirect (a rule ordering
    mistake) or a 5xx."""
    text = SMOKE.read_text(encoding="utf-8")
    assert "/favicon.ico" in text
    assert "not a server error" in text
    assert "is not redirected" in text
    # It must not be asserted as a 200, which would fail on every run.
    assert 'check "/favicon.ico returns 200"' not in text


def test_smoke_does_not_run_the_cleanup_by_default():
    text = SMOKE.read_text(encoding="utf-8")
    assert "--with-cleanup" in text
    assert "NSS_CONFIRM_CLEANUP" in text


# ---------------------------------------------------------------------------
# The sandbox
# ---------------------------------------------------------------------------

INSTALL_REWRITES = (
    ("/usr/local/sbin/nss-decommission", "{r}/usr/local/sbin/nss-decommission"),
    ("/etc/systemd/system/nss-inauguration.service", "{r}/etc/systemd/system/nss-inauguration.service"),
    ("/etc/sudoers.d/nss-inauguration", "{r}/etc/sudoers.d/nss-inauguration"),
    ("/etc/nginx/sites-available/nss", "{r}/etc/nginx/sites-available/nss"),
    ("/etc/nginx/sites-enabled/nss", "{r}/etc/nginx/sites-enabled/nss"),
    ("/etc/nginx/nss-mode.inc", "{r}/etc/nginx/nss-mode.inc"),
    ("/var/backups/nss-inauguration", "{r}/var/backups/nss-inauguration"),
    ("/var/log/nss-inauguration", "{r}/var/log/nss-inauguration"),
    ("/opt/nss-inauguration", "{r}/opt/nss-inauguration"),
    ("/usr/sbin/nginx", "{r}/stub/nginx"),
    ("/var/www/nss", "{r}/var/www/nss"),
)


class Sandbox:
    """A production layout in a temporary directory, with instrumented stubs."""

    def __init__(self, root: Path) -> None:
        self.root = root
        self.stub = root / "stub"
        self.probe = root / "probe.log"
        self.etc = root / "etc"
        self.web = root / "var" / "www" / "nss"
        self.opt = root / "opt" / "nss-inauguration"
        self.backups = root / "var" / "backups" / "nss-inauguration"
        self.src = root / "src"
        self.script = self.src / "deploy" / "install.sh"

        for path in (self.stub, self.probe.parent, self.web, self.src):
            path.mkdir(parents=True, exist_ok=True)

    # -- layout ------------------------------------------------------------

    @staticmethod
    def _write(path: Path, text: str) -> None:
        """Write the way Linux would: LF, never the host's CRLF."""
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")

    def build_site(self) -> None:
        for name in ("css", "js", "vendor", "assets", "admin"):
            (self.web / name).mkdir(parents=True, exist_ok=True)
        self._write(self.web / "index.html", "<html><title>NSS</title>permanent home</html>")
        self._write(self.web / "team.html", "<html>permanent team</html>")
        self._write(self.web / "nss_logo.jpg", "jpeg")
        self._write(self.web / "css" / "style.css", ":root{}")
        self._write(self.web / "js" / "main.js", "// main")
        self._write(self.web / "admin" / "old.html", "stale portal file")
        self._write(self.web / "inauguration.html", "<html>ceremony</html>")

    def build_source_tree(self) -> None:
        """A copy of the real deploy tree, so install.sh's SOURCE_DIR resolves here."""
        shutil.copytree(INAUGURATION / "backend", self.src / "backend")
        shutil.copytree(INAUGURATION / "web", self.src / "web")
        shutil.copytree(INAUGURATION / "deploy", self.src / "deploy")
        shutil.copy2(REPO / "inauguration.html", self.root / "inauguration.html")
        self._write(self.src / "README.md", "# runbook\n")

    def build_existing_config(self, site: str = "server { listen 80; }\n") -> None:
        """What a machine that already runs Nginx looks like.

        Note what is *not* created: nss-mode.inc. On a first install it genuinely
        does not exist, and on a re-install it is the backend's file to own — an
        installer that overwrote it would reset a live ceremony to coming_soon mode.
        """
        for directory in (
            self.etc / "nginx" / "sites-available",
            self.etc / "nginx" / "sites-enabled",
            self.etc / "systemd" / "system",
            self.etc / "sudoers.d",
        ):
            directory.mkdir(parents=True, exist_ok=True)
        self._write(self.etc / "nginx" / "sites-available" / "nss", site)

    def build_venv(self) -> None:
        """A venv whose python is a shim, so no package is ever downloaded.

        The shim also has to make the host behave like the VM. On Linux Python's
        stdout is UTF-8 with no newline translation; on Windows it is the ANSI code
        page and every ``\\n`` becomes ``\\r\\n``. The include contains an em dash and
        is compared byte for byte, so without this the test fails for a reason that
        cannot happen in production — the same trap the decommission sandbox hit.
        """
        python = self.opt / "venv" / "bin" / "python"
        self._write(
            python,
            "#!/bin/bash\n"
            "# Sandbox shim: pretend to install dependencies, and pass everything else\n"
            "# through to the real interpreter so the include really is rendered.\n"
            'if [ "$1" = "-m" ] && [ "$2" = "pip" ]; then exit 0; fi\n'
            'case "$2" in *"import fastapi"*) exit 0 ;; esac\n'
            f'PYTHONIOENCODING=utf-8 "{Path(sys.executable).as_posix()}" "$@" | tr -d "\\r"\n'
            "exit ${PIPESTATUS[0]}\n",
        )
        self._make_executable(python)

    # -- stubs -------------------------------------------------------------

    def _make_executable(self, path: Path) -> None:
        os.chmod(path, 0o755)
        if os.name == "nt":
            # MSYS decides `-x` partly on the extension; make the intent explicit.
            with open(path, "ab") as fh:
                fh.write(b"")

    def _stub(self, name: str, body: str) -> None:
        path = self.stub / name
        self._write(path, "#!/bin/bash\n" + body)
        self._make_executable(path)

    def build_stubs(self) -> None:
        probe = self.probe.as_posix()
        stub = self.stub.as_posix()

        self._stub("id", 'echo 0\n')
        # chown is the first thing that reaches outside the backup directory, so it
        # is instrumented: the probe line records how many snapshots already existed
        # when it ran, which is how the ordering claim below is made without relying
        # on filesystem timestamps.
        self._stub(
            "chown",
            f'echo "chown snapshots=$(ls -1 "{self.backups.as_posix()}" 2>/dev/null | wc -l)"'
            f' >> "{probe}"\nexit 0\n',
        )
        self._stub("useradd", f'echo "useradd $*" >> "{probe}"\nexit 0\n')
        self._stub("python3", "exit 0\n")
        self._stub("sudo", "exit 0\n")

        self._stub("systemctl", f'echo "systemctl $*" >> "{probe}"\nexit 0\n')

        # `install -o root` cannot work on the test host; keep everything else.
        self._stub(
            "install",
            "src=''; dst=''; mode=''\n"
            "while [ $# -gt 0 ]; do\n"
            "  case \"$1\" in\n"
            "    -o|-g) shift 2;;\n"
            "    -m) mode=\"$2\"; shift 2;;\n"
            "    -*) shift;;\n"
            "    *) if [ -z \"$src\" ]; then src=\"$1\"; else dst=\"$1\"; fi; shift;;\n"
            "  esac\n"
            "done\n"
            "[ -n \"$dst\" ] || exit 0\n"
            "if [ \"$src\" = /dev/null ]; then : > \"$dst\"; else cp \"$src\" \"$dst\"; fi\n"
            "[ -n \"$mode\" ] && chmod \"$mode\" \"$dst\"\n"
            "exit 0\n",
        )

        self._stub(
            "nginx",
            f'echo "nginx $*" >> "{probe}"\n'
            f'if [ "$1" = "-t" ] && [ -f "{stub}/fail-test" ]; then\n'
            '  echo "nginx: [emerg] invalid location modifier" >&2; exit 1\n'
            "fi\n"
            f'if [ "$1" = "-s" ] && [ -f "{stub}/fail-reload" ]; then\n'
            '  echo "nginx: [error] reload failed" >&2; exit 1\n'
            "fi\n"
            "exit 0\n",
        )

        self._stub(
            "visudo",
            f'if [ -f "{stub}/fail-visudo" ]; then\n'
            '  echo "syntax error" >&2; exit 1\n'
            "fi\n"
            "exit 0\n",
        )

        self._stub(
            "curl",
            "url=''\n"
            "while [ $# -gt 0 ]; do\n"
            "  case \"$1\" in\n"
            "    -H|--max-time|-o|-w) shift 2;;\n"
            "    -*) shift;;\n"
            "    *) url=\"$1\"; shift;;\n"
            "  esac\n"
            "done\n"
            f'echo "curl $url" >> "{probe}"\n'
            'printf \'{"ok":true,"site_mode":"coming_soon"}\'\n'
            "exit 0\n",
        )

    # -- the script under test --------------------------------------------

    def build_script(self) -> Path:
        text = INSTALL.read_text(encoding="utf-8")
        root = self.root.as_posix()
        for old, new in INSTALL_REWRITES:
            text = text.replace(old, new.format(r=root))
        self._write(self.script, text)
        self._make_executable(self.script)
        return self.script

    # -- running -----------------------------------------------------------

    def run(self, *args: str) -> subprocess.CompletedProcess:
        env = dict(os.environ)
        env["PATH"] = self.stub.as_posix() + os.pathsep + env.get("PATH", "")
        # stdin is closed rather than inherited: install.sh must never prompt, and a
        # child that waits on a terminal would hang here instead of failing.
        return subprocess.run(
            [BASH, self.script.as_posix(), *args],
            capture_output=True, text=True, env=env, timeout=180,
            stdin=subprocess.DEVNULL,
        )

    def probes(self) -> list[str]:
        if not self.probe.exists():
            return []
        return [line for line in self.probe.read_text(encoding="utf-8").splitlines() if line.strip()]

    def full(self) -> "Sandbox":
        self.build_site()
        self.build_source_tree()
        self.build_existing_config()
        self.build_venv()
        self.build_stubs()
        self.build_script()
        return self


@pytest.fixture
def sandbox(tmp_path: Path) -> Sandbox:
    return Sandbox(tmp_path).full()


# ---------------------------------------------------------------------------
# install.sh, run for real
# ---------------------------------------------------------------------------


def test_install_succeeds_and_wires_the_whole_system_up(sandbox: Sandbox):
    result = sandbox.run()
    assert result.returncode == 0, f"install failed:\n{result.stdout}\n{result.stderr}"

    # The application and its venv.
    assert (sandbox.opt / "app" / "main.py").is_file()
    assert (sandbox.opt / "app" / "nginx_mode.py").is_file()
    assert (sandbox.opt / "config" / "nss.env").is_file()

    # The temporary web files, and the stale portal file gone.
    assert (sandbox.web / "coming-soon.html").is_file()
    assert (sandbox.web / "admin" / "index.html").is_file()
    assert not (sandbox.web / "admin" / "old.html").exists(), "the old portal was not cleared"

    # The cleanup script, the unit and the rule.
    assert (sandbox.root / "usr" / "local" / "sbin" / "nss-decommission").is_file()
    assert (sandbox.etc / "systemd" / "system" / "nss-inauguration.service").is_file()
    assert (sandbox.etc / "sudoers.d" / "nss-inauguration").is_file()

    # The routing include was rendered by the real application, not copied.
    include = (sandbox.etc / "nginx" / "nss-mode.inc").read_text(encoding="utf-8")
    assert "coming-soon.html" in include
    assert "location = /coming-soon.html { }" in include, (
        "the hold page is not exempt from the .html catch-all — this is the redirect loop"
    )

    # The server block is in place and the site is enabled.
    assert (sandbox.etc / "nginx" / "sites-available" / "nss").is_file()
    assert (sandbox.etc / "nginx" / "sites-enabled" / "nss").exists()

    # ...and it was tested before it was reloaded.
    probes = sandbox.probes()
    assert any(p.startswith("nginx -t") for p in probes)
    assert any(p.startswith("nginx -s reload") for p in probes)
    assert [p.split()[1] for p in probes if p.startswith("nginx")][:2] == ["-t", "-s"], (
        f"nginx was reloaded before it was tested: {probes}"
    )
    assert any("curl" in p and "/api/health" in p for p in probes), "the health check never ran"


def test_install_ships_the_ceremony_page(sandbox: Sandbox):
    """The ceremony page is deployed, from the one copy that is its source.

    It used to be left alone here, on the reasoning that a deploy should never
    change what the ceremony looks like. The effect was the opposite: a fix to
    the page could not be deployed at all. The web root kept whatever it happened
    to be holding and the ceremony ran that, while the preflight insisted on a
    file — ``$REPO_DIR/inauguration.html`` — that nothing ever copied. That file
    is now what the web root gets, and the page it replaces stays in the snapshot.
    """
    result = sandbox.run()
    assert result.returncode == 0, result.stderr

    assert (sandbox.web / "inauguration.html").read_bytes() == (
        sandbox.root / "inauguration.html"
    ).read_bytes(), "the ceremony page at the web root is not the one in the repo"

    snapshots = sorted(p for p in sandbox.backups.iterdir() if p.name.startswith("deploy-"))
    replaced = snapshots[0] / "site" / "inauguration.html"
    assert replaced.is_file(), "the ceremony page the install replaced was not kept"
    assert "ceremony</html>" in replaced.read_text(encoding="utf-8"), (
        "the snapshot does not hold the page that was actually there"
    )


def test_install_snapshots_the_site_before_replacing_anything(sandbox: Sandbox):
    result = sandbox.run()
    assert result.returncode == 0, result.stderr

    snapshots = sorted(p for p in sandbox.backups.iterdir() if p.name.startswith("deploy-"))
    assert len(snapshots) == 1, f"expected one snapshot, found {snapshots}"
    snapshot = snapshots[0]

    assert (snapshot / "site" / "index.html").is_file()
    assert (snapshot / "site" / "admin" / "old.html").is_file(), (
        "the snapshot must hold the site as it was, including what the install removes"
    )
    assert (snapshot / "nginx" / "nss").is_file()

    check = subprocess.run(
        [BASH, "-c", "sha256sum --check --quiet MANIFEST.sha256"],
        cwd=snapshot.as_posix(), capture_output=True, text=True,
    )
    assert check.returncode == 0, "the snapshot does not verify against its own manifest"


def test_a_failed_nginx_test_leaves_the_live_config_byte_identical(sandbox: Sandbox):
    """The rule this whole script exists to keep."""
    live = sandbox.etc / "nginx" / "sites-available" / "nss"
    before = live.read_bytes()
    (sandbox.stub / "fail-test").write_text("", encoding="utf-8")

    result = sandbox.run()
    assert result.returncode != 0, "install succeeded despite nginx rejecting the config"
    assert "nginx rejected the new server block" in result.stderr or \
           "nginx rejected the new server block" in result.stdout

    assert live.read_bytes() == before, "the live configuration was not restored byte for byte"
    assert not any(p.startswith("nginx -s reload") for p in sandbox.probes()), (
        "the site was reloaded with a configuration nginx had just rejected"
    )


def test_a_failed_nginx_reload_restores_the_previous_configuration(sandbox: Sandbox):
    live = sandbox.etc / "nginx" / "sites-available" / "nss"
    before = live.read_bytes()
    (sandbox.stub / "fail-reload").write_text("", encoding="utf-8")

    result = sandbox.run()
    assert result.returncode != 0
    assert live.read_bytes() == before, "a failed reload left the new configuration in place"

    probes = sandbox.probes()
    assert any(p.startswith("nginx -t") for p in probes)
    assert any(p.startswith("nginx -s reload") for p in probes), "no reload was attempted"


def test_install_snapshots_before_it_touches_the_live_system(sandbox: Sandbox):
    """Nothing outside the backup directory may be modified before the way back
    exists.

    Proven from the probe log rather than by reading the source. ``chown`` is the
    first thing the script runs that reaches outside the snapshot, and each chown
    records how many snapshots existed at that moment — so if the order ever
    inverts, the first line reads 0.
    """
    result = sandbox.run()
    assert result.returncode == 0, result.stderr

    chowns = [line for line in sandbox.probes() if line.startswith("chown ")]
    assert chowns, "the chown stub never ran; this test has stopped testing anything"
    assert chowns[0].endswith("snapshots=1"), (
        f"the live system was modified before the snapshot was written: {chowns[0]}"
    )


def test_a_reinstall_does_not_reset_a_live_ceremony(sandbox: Sandbox):
    """The routing include belongs to the backend, not to the installer.

    Re-running install.sh during the ceremony must not rewrite the include back to
    coming_soon and abort the event — which is exactly what would happen if the
    installer treated it as its own file.
    """
    result = sandbox.run()
    assert result.returncode == 0, result.stderr
    include = sandbox.etc / "nginx" / "nss-mode.inc"
    include.write_text("# ceremony routing, mid-event\n", encoding="utf-8")

    result = sandbox.run()
    assert result.returncode == 0, result.stderr
    assert include.read_text(encoding="utf-8") == "# ceremony routing, mid-event\n", (
        "the installer overwrote routing that the backend owns"
    )


def test_install_refuses_a_broken_sudoers_rule(sandbox: Sandbox):
    """A bad rule must abort the install, not be installed and hoped over."""
    (sandbox.stub / "fail-visudo").write_text("", encoding="utf-8")
    result = sandbox.run()
    assert result.returncode != 0
    assert "the sudoers rule is invalid" in result.stderr + result.stdout
    assert not (sandbox.etc / "sudoers.d" / "nss-inauguration").exists()
    # ...and the sandbox never gained a .candidate left behind.
    assert not (sandbox.etc / "sudoers.d" / "nss-inauguration.candidate").exists()


def test_install_refuses_arguments(sandbox: Sandbox):
    result = sandbox.run("--force")
    assert result.returncode != 0
    assert "takes no arguments" in result.stderr + result.stdout


def test_install_refuses_a_web_root_that_is_not_there(sandbox: Sandbox):
    shutil.rmtree(sandbox.web)
    result = sandbox.run()
    assert result.returncode != 0
    assert "does not exist" in result.stderr + result.stdout


# ---------------------------------------------------------------------------
# rollback.sh, run for real
# ---------------------------------------------------------------------------


class RollbackSandbox(Sandbox):
    """The same layout, plus snapshots to roll back to."""

    def build_rollback(self) -> Path:
        self.rollback = self.root / "rollback.sh"
        text = ROLLBACK.read_text(encoding="utf-8")
        root = self.root.as_posix()
        for old, new in INSTALL_REWRITES:
            text = text.replace(old, new.format(r=root))
        self._write(self.rollback, text)
        self._make_executable(self.rollback)
        return self.rollback

    def snapshot(self, name: str, include: str, site: str, *, when: str) -> Path:
        """A deploy-style snapshot, dated explicitly.

        The mtime is set rather than inherited from creation order: rollback.sh picks
        the newest by `ls -1dt`, and filesystem timestamps have a resolution too coarse
        to rely on for two directories made a millisecond apart.
        """
        directory = self.backups / name
        self._write(directory / "nginx" / "nss-mode.inc", include)
        self._write(directory / "nginx" / "nss", site)
        self._write(directory / "site" / "index.html", f"<html>{name}</html>")

        subprocess.run(
            [BASH, "-c",
             "find . -type f ! -name MANIFEST.sha256 -print0 | sort -z "
             "| xargs -0 -r sha256sum > MANIFEST.sha256"],
            cwd=directory.as_posix(), check=True, capture_output=True,
        )
        subprocess.run(
            [BASH, "-c", f'touch -d "{when}" "{directory.as_posix()}"'],
            check=True, capture_output=True,
        )
        return directory

    def run_rollback(self, *args: str) -> subprocess.CompletedProcess:
        env = dict(os.environ)
        env["PATH"] = self.stub.as_posix() + os.pathsep + env.get("PATH", "")
        return subprocess.run(
            [BASH, self.rollback.as_posix(), *args],
            capture_output=True, text=True, env=env, timeout=120,
            stdin=subprocess.DEVNULL,
        )

    def full(self) -> "RollbackSandbox":
        super().full()
        self.build_rollback()
        return self


@pytest.fixture
def rollback_box(tmp_path: Path) -> RollbackSandbox:
    return RollbackSandbox(tmp_path).full()


def test_rollback_restores_the_newest_snapshot(rollback_box: RollbackSandbox):
    rollback_box.snapshot(
        "deploy-20260101T000000Z", "# old routing\n", "server { listen 80; }\n",
        when="2020-01-01 00:00:00",
    )
    newest = rollback_box.snapshot(
        "deploy-20260102T000000Z", "# good routing\n", "server { listen 443 ssl; }\n",
        when="2030-01-01 00:00:00",
    )

    # The site is broken: a bad transition left routing that does not work.
    include = rollback_box.etc / "nginx" / "nss-mode.inc"
    include.write_text("# broken\n", encoding="utf-8")
    site = rollback_box.etc / "nginx" / "sites-available" / "nss"
    site.write_text("server { broken }\n", encoding="utf-8")

    result = rollback_box.run_rollback()
    assert result.returncode == 0, f"rollback failed:\n{result.stdout}\n{result.stderr}"

    assert include.read_text(encoding="utf-8") == "# good routing\n"
    assert site.read_text(encoding="utf-8") == "server { listen 443 ssl; }\n"

    probes = rollback_box.probes()
    nginx_calls = [p.split()[1] for p in probes if p.startswith("nginx")]
    assert nginx_calls[:2] == ["-t", "-s"], (
        f"nginx was reloaded before the restored config was tested: {probes}"
    )
    assert "deploy-20260102T000000Z" in result.stdout
    # The state it replaced is kept, so a wrong rollback is itself reversible.
    assert "pre-rollback-" in result.stdout


def test_rollback_refuses_a_snapshot_that_fails_its_checksums(rollback_box: RollbackSandbox):
    """Restoring from a damaged snapshot could put a half-written file live, which is
    worse than the state it was meant to fix."""
    directory = rollback_box.snapshot(
        "deploy-20260101T000000Z", "# good routing\n", "server { listen 80; }\n",
        when="2020-01-01 00:00:00",
    )
    include = rollback_box.etc / "nginx" / "nss-mode.inc"
    include.write_text("# current\n", encoding="utf-8")

    # Something corrupted the snapshot after it was taken.
    (directory / "nginx" / "nss-mode.inc").write_text("# tampered\n", encoding="utf-8")

    result = rollback_box.run_rollback("--backup", "deploy-20260101T000000Z")
    assert result.returncode != 0
    assert "does not match its own checksums" in result.stderr + result.stdout
    assert include.read_text(encoding="utf-8") == "# current\n", "a bad snapshot was restored"
    assert not any(p.startswith("nginx -s reload") for p in rollback_box.probes())


def test_rollback_leaves_the_web_root_alone_by_default(rollback_box: RollbackSandbox):
    """The site's content is not what breaks, and rewriting it during an incident
    would undo whatever the ceremony had legitimately done."""
    rollback_box.snapshot(
        "deploy-20260101T000000Z", "# good routing\n", "server { listen 80; }\n",
        when="2020-01-01 00:00:00",
    )
    live = rollback_box.web / "index.html"
    live.write_text("<html>what the ceremony made</html>", encoding="utf-8")

    result = rollback_box.run_rollback()
    assert result.returncode == 0, result.stderr
    assert live.read_text(encoding="utf-8") == "<html>what the ceremony made</html>"


def test_rollback_restores_the_web_root_when_asked(rollback_box: RollbackSandbox):
    rollback_box.snapshot(
        "deploy-20260101T000000Z", "# good routing\n", "server { listen 80; }\n",
        when="2020-01-01 00:00:00",
    )
    live = rollback_box.web / "index.html"
    live.write_text("<html>broken by the deploy</html>", encoding="utf-8")

    result = rollback_box.run_rollback("--web")
    assert result.returncode == 0, result.stderr
    assert live.read_text(encoding="utf-8") == "<html>deploy-20260101T000000Z</html>"


def test_a_rejected_restore_puts_the_previous_routing_back(rollback_box: RollbackSandbox):
    """If the snapshot itself is what Nginx rejects, the machine must not be left with
    routing that does not work."""
    rollback_box.snapshot(
        "deploy-20260101T000000Z", "# snapshot routing\n", "server { listen 80; }\n",
        when="2020-01-01 00:00:00",
    )
    include = rollback_box.etc / "nginx" / "nss-mode.inc"
    include.write_text("# what was live and working\n", encoding="utf-8")

    (rollback_box.stub / "fail-test").write_text("", encoding="utf-8")
    result = rollback_box.run_rollback()
    assert result.returncode != 0
    assert include.read_text(encoding="utf-8") == "# what was live and working\n", (
        "the machine was left on routing nginx had just rejected"
    )


def test_rollback_lists_snapshots(rollback_box: RollbackSandbox):
    rollback_box.snapshot(
        "deploy-20260101T000000Z", "# a\n", "server { }\n", when="2020-01-01 00:00:00",
    )
    rollback_box.snapshot(
        "cleanup-20261002-101500", "# b\n", "server { }\n", when="2020-01-02 00:00:00",
    )
    result = rollback_box.run_rollback("--list")
    assert result.returncode == 0
    assert "deploy-20260101T000000Z" in result.stdout
    assert "cleanup-20261002-101500" in result.stdout


def test_rollback_refuses_an_unknown_argument(rollback_box: RollbackSandbox):
    result = rollback_box.run_rollback("--pretend")
    assert result.returncode != 0
    assert "unknown argument" in result.stderr + result.stdout


def test_rollback_says_so_when_there_is_nothing_to_roll_back_to(rollback_box: RollbackSandbox):
    result = rollback_box.run_rollback()
    assert result.returncode != 0
    assert "no snapshots" in result.stderr + result.stdout
