"""The generated routing include.

Two of these are regression tests for bugs that produce a blank page rather than an
error, so they are worth having even though they only inspect text:

* the ``.html`` catch-all also matching the page it redirects to (an infinite loop),
* an unqualified ``location /`` swallowing the root-level logo and favicon.
"""

from __future__ import annotations

import pytest

from app.nginx_mode import NginxController, render_include
from conftest import FakeNginx

MODES = ("coming_soon", "inauguration", "permanent")


def _index(text: str, needle: str) -> int:
    assert needle in text, f"{needle!r} missing from the include"
    return text.index(needle)


# --- structure --------------------------------------------------------------


@pytest.mark.parametrize("mode", MODES)
def test_every_mode_renders(mode):
    assert "location" in render_include(mode)


def test_an_unknown_mode_is_rejected():
    with pytest.raises(ValueError):
        render_include("nonsense")


@pytest.mark.parametrize("mode", ["coming_soon", "inauguration"])
def test_the_redirect_target_is_exempt_from_the_catch_all(mode):
    """Without the exact-match block the redirect points at itself and loops."""
    text = render_include(mode)
    page = "/coming-soon.html" if mode == "coming_soon" else "/inauguration.html"
    assert _index(text, f"location = {page} ") < _index(text, "location ~* \\.html$")


@pytest.mark.parametrize("mode", ["coming_soon", "inauguration"])
def test_root_level_assets_are_not_redirected(mode):
    """The logo sits beside the pages, not in a directory; `location /` would eat it."""
    text = render_include(mode)
    assert "location = /nss_logo.jpg" in text
    assert "location = /favicon.ico" in text
    assert _index(text, "location = /nss_logo.jpg") < _index(text, "location /")


@pytest.mark.parametrize("mode", ["coming_soon", "inauguration"])
@pytest.mark.parametrize("prefix", ["/assets/", "/css/", "/js/", "/vendor/", "/admin/"])
def test_asset_prefixes_are_present(mode, prefix):
    assert f"location ^~ {prefix}" in render_include(mode)


@pytest.mark.parametrize("mode", ["coming_soon", "inauguration"])
def test_no_bare_location_precedes_a_prefix_block(mode):
    """A bare `location /` earlier in the file would shadow every `^~` block after it."""
    text = render_include(mode)
    bare = text.index("location / ")
    for prefix in ("/assets/", "/css/", "/js/", "/vendor/", "/admin/", "/api/"):
        assert text.index(f"location ^~ {prefix}") < bare


def test_coming_soon_hides_the_ceremony_page():
    text = render_include("coming_soon")
    assert "location = /inauguration.html { return 302 /coming-soon.html; }" in text


def test_inauguration_retires_the_hold_page():
    text = render_include("inauguration")
    assert "location = /coming-soon.html { return 302 /; }" in text


def test_permanent_has_no_backend_at_all():
    """The end state must not depend on the service it is about to outlive."""
    text = render_include("permanent")
    assert "proxy_pass" not in text
    assert "/admin/" not in text
    assert "/api/" not in text
    assert "/preview" not in text
    assert "try_files $uri $uri/ =404;" in text


@pytest.mark.parametrize("mode", ["coming_soon", "inauguration"])
def test_the_preview_is_proxied_to_the_backend(mode):
    text = render_include(mode)
    assert "location = /preview" in text
    assert "/api/admin/preview" in text


def test_the_include_says_it_is_generated():
    assert render_include("permanent").startswith("# Generated by nss-inauguration")


# --- applying ---------------------------------------------------------------


def test_applying_a_mode_writes_and_reloads(settings, nginx):
    result = NginxController(settings, run=nginx).apply("inauguration")
    assert result.ok and result.changed
    assert settings.nginx_mode_inc.read_text(encoding="utf-8") == render_include("inauguration")
    assert nginx.tests == 1 and nginx.reloads == 1


def test_applying_the_same_mode_twice_does_not_reload(settings, nginx):
    controller = NginxController(settings, run=nginx)
    controller.apply("inauguration")
    second = controller.apply("inauguration")
    assert second.ok and not second.changed
    assert nginx.reloads == 1


def test_a_failed_config_test_restores_the_previous_bytes(settings):
    """Nothing is live until the reload, so a rejection must leave the site untouched."""
    previous = "    location / { return 302 /old; }\n"
    settings.nginx_mode_inc.parent.mkdir(parents=True, exist_ok=True)
    settings.nginx_mode_inc.write_text(previous, encoding="utf-8")

    failing = FakeNginx(test_ok=False)
    result = NginxController(settings, run=failing).apply("permanent")

    assert not result.ok
    assert settings.nginx_mode_inc.read_text(encoding="utf-8") == previous
    assert failing.reloads == 0, "a config that failed the test must never be reloaded"


def test_a_failed_test_on_a_first_apply_removes_the_new_file(settings):
    failing = FakeNginx(test_ok=False)
    result = NginxController(settings, run=failing).apply("permanent")
    assert not result.ok
    assert not settings.nginx_mode_inc.exists()


def test_a_failed_reload_rolls_back(settings, nginx):
    previous = "    location / { return 302 /old; }\n"
    settings.nginx_mode_inc.parent.mkdir(parents=True, exist_ok=True)
    settings.nginx_mode_inc.write_text(previous, encoding="utf-8")

    controller = NginxController(settings, run=nginx)
    controller.apply("coming_soon")  # establishes a known-good state

    good = settings.nginx_mode_inc.read_text(encoding="utf-8")
    nginx.reload_ok = False
    result = controller.apply("permanent")

    assert not result.ok
    assert settings.nginx_mode_inc.read_text(encoding="utf-8") == good


def test_a_missing_nginx_binary_is_reported_not_raised(settings):
    def boom(*args, **kwargs):
        raise FileNotFoundError("nginx")

    result = NginxController(settings, run=boom).apply("permanent")
    assert not result.ok
    assert "not found" in result.message
