"""Rendering and applying the Nginx routing include.

The include is a fragment of ``location`` blocks, pulled into the server block by
``sites-available/nss``. It is regenerated whenever the site mode changes, and the
new version is always tested *before* it can take effect: ``nginx -t`` reads the file
from disk, so writing a candidate and testing it is safe — nginx does not act on it
until the reload, and a failed test restores the previous bytes.

Two traps this file exists to avoid, both of which produce a blank page rather than
an error:

* A ``location ~* \\.html$`` catch-all also matches the hold page itself, so the
  redirect target must have an exact-match block that wins over the regex.
* Root-level permanent assets (``/nss_logo.jpg``) are not under any ``^~`` prefix, so
  an unqualified ``location /`` would redirect them too and strip the branding.
"""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Sequence

from .config import Settings
from .state import MODES

HEADER = "# Generated by nss-inauguration. Do not edit by hand — it is rewritten on every mode change.\n"

#: Prefixes served straight from disk in every non-permanent mode. `^~` makes the
#: prefix win over the regex locations that follow, which is what keeps `/admin/` and
#: the asset directories reachable while `.html` requests are still being redirected.
_ASSET_PREFIXES = ("/assets/", "/css/", "/js/", "/vendor/")

#: Root-level files that live beside the pages rather than in a directory, and so are
#: not reached by any ``^~`` prefix. Exempting them is what stops an unqualified
#: ``location /`` redirect from 302ing ``/nss_logo.jpg`` and stripping the branding
#: off the hold page.
#:
#: ``/favicon.ico`` is in this list as an *exemption*, not a claim that the file
#: exists — it does not, and never has. Its purpose is that a request for it must not
#: be redirected and must not error; a 404 straight off disk is the correct answer.
#: `deploy/smoke.sh` asserts exactly that, and deliberately does not assert a 200.
_ROOT_ASSETS = ("/nss_logo.jpg", "/favicon.ico")

#: Every path that must answer in every mode. The smoke script and the pytest
#: structural test both read this, so there is one list to keep honest.
REQUIRED_REACHABLE = (
    "/coming-soon.html",
    "/nss_logo.jpg",
    "/css/style.css",
    "/js/main.js",
    "/vendor/gsap.min.js",
    "/assets/",
)

_API_PROXY = "        proxy_pass http://127.0.0.1:8001;\n"

#: The admin preview of the ceremony, served by the backend rather than by an Nginx
#: auth_request. The authorization check is then an ordinary FastAPI dependency —
#: testable locally, and one fewer Nginx feature that can only be verified on the VM.
_PREVIEW_PROXY = (
    "    location = /preview {\n"
    "        proxy_pass http://127.0.0.1:8001/api/admin/preview;\n"
    "    }\n"
)


def _prefix_blocks() -> str:
    out = ""
    for prefix in _ASSET_PREFIXES:
        out += f"    location ^~ {prefix} {{ }}\n"
    return out


def _root_asset_blocks() -> str:
    return "".join(f"    location = {p} {{ }}\n" for p in _ROOT_ASSETS)


def render_include(mode: str) -> str:
    """Return the include body for a mode.

    Ordering is load-bearing and deliberate; see the module docstring. Do not
    reorder without re-reading it.
    """
    if mode not in MODES:
        raise ValueError(f"unknown mode {mode!r}")

    if mode == "permanent":
        # The end state. No backend, no portal, no ceremony — nothing that can fail
        # after the inauguration system is gone.
        return HEADER + (
            "    location / {\n"
            "        try_files $uri $uri/ =404;\n"
            "    }\n"
        )

    if mode == "coming_soon":
        page = "/coming-soon.html"
        # Requests for the ceremony page must not be served early.
        extra = "    location = /inauguration.html { return 302 /coming-soon.html; }\n"
    else:  # inauguration
        page = "/inauguration.html"
        # The hold page is done; anyone with it bookmarked goes to the ceremony.
        extra = "    location = /coming-soon.html { return 302 /; }\n"

    return HEADER + (
        f"    # The page at / must be exempt from the catch-all below, or the\n"
        f"    # redirect would point at itself and loop.\n"
        f"    location = {page} {{ }}\n"
        f"{extra}"
        f"    location = / {{\n"
        f"        rewrite ^ {page} last;\n"
        f"    }}\n"
        f"{_root_asset_blocks()}"
        f"{_prefix_blocks()}"
        f"{_PREVIEW_PROXY}"
        f"    location ^~ /admin/ {{ }}\n"
        f"    location ^~ /api/ {{\n"
        f"{_API_PROXY}"
        f"    }}\n"
        f"    # Everything else that is a page goes back to the hold.\n"
        f"    location ~* \\.html$ {{ return 302 {page}; }}\n"
        f"    location / {{ return 302 {page}; }}\n"
    )


@dataclass
class NginxResult:
    ok: bool
    changed: bool
    message: str


class NginxController:
    """Applies a mode, testing before the change can take effect.

    ``run`` is injectable so the test suite can drive the failure paths — a failing
    ``nginx -t``, a failing reload — without an nginx binary present.
    """

    def __init__(self, settings: Settings, run: Callable[..., object] | None = None) -> None:
        self.settings = settings
        self._run = run if run is not None else subprocess.run

    # -- primitives ---------------------------------------------------------

    def test(self) -> tuple[bool, str]:
        return self._invoke([self.settings.nginx_binary, "-t"])

    def reload(self) -> tuple[bool, str]:
        return self._invoke([self.settings.nginx_binary, "-s", "reload"])

    def _invoke(self, cmd: Sequence[str]) -> tuple[bool, str]:
        try:
            proc = self._run(
                list(cmd), capture_output=True, text=True, check=False
            )
        except FileNotFoundError:
            return False, f"{cmd[0]} not found"
        except OSError as exc:
            return False, str(exc)

        ok = getattr(proc, "returncode", 1) == 0
        output = (getattr(proc, "stderr", "") or "") + (getattr(proc, "stdout", "") or "")
        return ok, output.strip()

    # -- the operation ------------------------------------------------------

    def apply(self, mode: str) -> NginxResult:
        """Point the include at ``mode``, or leave the system exactly as it was."""
        candidate = render_include(mode)
        path: Path = self.settings.nginx_mode_inc

        previous: str | None = None
        try:
            previous = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            previous = None

        if previous == candidate:
            return NginxResult(True, False, f"already in {mode} mode")

        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(candidate, encoding="utf-8")
        except OSError as exc:
            return NginxResult(False, False, f"could not write {path}: {exc}")

        def restore() -> str:
            if previous is None:
                try:
                    path.unlink()
                except OSError:
                    pass
                return "removed the new include"
            path.write_text(previous, encoding="utf-8")
            return "restored the previous include"

        ok, output = self.test()
        if not ok:
            # Nothing was live yet — nginx reads the file on reload, which we have
            # not done. Put the old bytes back and report.
            restore()
            return NginxResult(False, False, f"nginx -t rejected the new routing: {output}")

        ok, output = self.reload()
        if not ok:
            note = restore()
            # The old configuration was already known-good, so this second reload
            # returns the site to a working state rather than a half-applied one.
            again_ok, again_out = self.test()
            if again_ok:
                self.reload()
            return NginxResult(
                False,
                False,
                f"nginx reload failed ({output}); {note}; re-test {'passed' if again_ok else 'failed: ' + again_out}",
            )

        return NginxResult(True, True, f"site mode is now {mode}")


__all__ = [
    "render_include",
    "NginxController",
    "NginxResult",
    "REQUIRED_REACHABLE",
]
